version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: athena-spooty_server_1
      APP_PORT: 8989

  server:
    image: raiper34/spooty:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/downloads:/downloads
